### ISSUE TITLE
Roms crash in SPU.cpp SPU_CloneUser()

### ISSUE THREAD

**Issue by Joride** [NitrogenEmulator/Nitrogen#20]
Crash in:
SPU.cpp - SPU_CloneUser()
line236: 
memcpy(SPU_user->channels,SPU_core->channels,sizeof(SPU_core->channels));

"Thread 1: EXC_BAD_ACCESS"

Diagnostics:
iOS device: iPhone 6 Plus
iOS version: iOS 8.1.3 (12B466)
Jailbreak status: not jailbroken
Download location: ROMs downloaded from emu paradise.com

Roms tested:
- 0333 - Super Monkey Ball - Touch & Roll (U)(Trashman)
- 0037 - Super Mario 64 DS (U)(Trashman) 2
- 0434 - New Super Mario Bros. (U)(Psyfer)
- 1456 - Legend of Zelda - Phantom Hourglass, The (U)(Independent)

**Comment by fnsroot** [comment]
Had the same issue: here a "dirty fix".
Line 260:
[...]
delete SPU_user;
    SPU_user = NULL;

```
if(synchmode == ESynchMode_DualSynchAsynch)
{
    SPU_user = new SPU_struct(buffersize);
    //SPU_CloneUser(); <-- comment out this line, line 260

}
```

}

[...]

**Comment by Joride** [comment]
Great, this makes the ROMs run. Can you explain briefly what I just changed?

**Comment by nintyapple** [comment]
@fnsroot Good workaround, but seems to crash settings when opened.
