### ISSUE TITLE
nds4ios

### ISSUE THREAD

**Issue by nrubin29** [NitrogenEmulator/Nitrogen#21]
-- Read below first. --

Nitrogen is an exact clone of nds4ios, from the layout to the ReadMe to the hidden settings secret (triple tap the top right of the screen). For those of you who don't know about it, nds4ios was the original DS emulator for iOS. It lasted for a few years before being DMCA'd by Nintendo.

I first want to point out that the Nitrogen team has done little to no work to create this emulator. That distinctions goes to the InfiniDev team. Second of all, don't be surprised if this doesn't last long. nds4ios was taken down and this is the exact same.

**Comment by tduquer** [comment]
But this one will have mic, won't it?

**Comment by inb4ohnoes** [comment]
We're most of the same people who created nds4ios, just under a different name. Now that we're not using a name that references Nintendo or its product directly, we should be mostly fine.

**Comment by nrubin29** [comment]
I thought I recognized you. I noticed that the about section was devoid of names so I got worried. Should I remove nds4ios and replace it with Nitrogen?

**Comment by inb4ohnoes** [comment]
It doesn't matter.
