### ISSUE TITLE
Crash when launching a ROM on iOS 8.3

### ISSUE THREAD

**Issue by benjamincrozat** [NitrogenEmulator/Nitrogen#23]
Hello,

Thank you for making this emulator. I wanted to get my hands on it so I compiled it and tried to launch a game but it crashes as soon as I select a game. Tried on iPhone 5c and iPad mini. I gave up to try it on my 6 Plus. Any tip for this problem?

**Comment by Gito12** [comment]
Hello i am running an I5 IOS 8.1.2 Jailbroken and i am also facing the same issue where the application will crash at launch when opening a ROM

**Comment by sethhoward** [comment]
Try turning off audio sync

**Comment by vixducis** [comment]
EDIT: this seems to bo related to another issue, please ignore my comment.

I have the same issue, please to look at the attached screenshot for where it went wrong. I'm running on the iPad 4, iOS 8.3, non-jailbroken, with the all-new free provisioning of Xcode 7.

![schermafbeelding 2015-06-10 om 21 02 12](https://cloud.githubusercontent.com/assets/378998/8091420/10c3a0cc-0fb4-11e5-8d21-f620ec0c1d48.png)

**Comment by sofakng** [comment]
Exact same issue and breaks at the same spot as vixducis.

I'm running iOS 8.3 on my iPad Air 2.  It crashes immediately after selecting a ROM.

EDIT: I've also tried disabling sound and synchronous audio is also off.

**Comment by tragessere** [comment]
In case anyone is still using this, I just commented out the entire `if` statement and it seems to be working fine. (Though I honestly have no idea what the repercussions of this are)

Anyway, the code to comment out is:

Nitrogen/Main/DeSmuME/SPU.cpp
lines: 235-238

(I guess this was mentioned in the other issue thread, but I'll leave this here anyway)

**Comment by yoshisuga** [comment]
If you comment out the entire if statement, you don't get sound when resuming from a save state.

The SPU_core is NULL when it crashes, so to fix this, I changed it to the following:

```
    if(SPU_user && SPU_core) {
        memcpy(SPU_user->channels,SPU_core->channels,sizeof(SPU_core->channels));
        SPU_user->regs = SPU_core->regs;
    }
```

I now get sound when resuming from a save state :)

**Comment by her** [comment]
yoshisuga thanks for the edit here this allowed me to launch the game however after a quick restart all sound has cut off now. 

iOS 9.0.1 iPhone 6 

PS after changing this line and adding "$$ SPU_core" Xcode reported nearly 200 fewer (!) issues when compiling
