### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by her** [NitrogenEmulator/Nitrogen#31]
I'd like to help out, but I see no recent commits or pulls... 

Is there another more active repository?

Thanks!

**Comment by inb4ohnoes** [comment]
No, it's not abandoned. If you want to help out, you can start making some pull requests.

**Comment by her** [comment]
Okay great :) 

Do you guys have an IRC or a Slack team setup? 

I'm not really sure where to start, or what you all might be working on already. so far I've just been going through the code and reading comments trying to understand the overall direction. 

I like the project a lot and just want to help out as much as possible!
