### ISSUE TITLE
Unable to install to device

### ISSUE THREAD

**Issue by drewbyhk** [NitrogenEmulator/Nitrogen#34]
Device: iPhone 6 on iOS 9.1
Xcode Version: 7.1

Whenever I try to install to my device, I get an error that the application does not support iOS 9.1. Please help!

**Comment by pachpage** [comment]
Same here.
![image](https://cloud.githubusercontent.com/assets/11856776/10711921/7525e746-7a58-11e5-8a5c-2b2444cd4b5a.png)

**Comment by drewbyhk** [comment]
@pachpage Yeah, that's the error I got.

**Comment by inb4ohnoes** [comment]
You must be signed into a free developer account. Xcode must provision your device from a free account or it wont install.

**Comment by drewbyhk** [comment]
lel idk i just followed this tutorial by operationidroid. https://youtu.be/hfno95Jraew
